### ISSUE TITLE
标记点MarkerClick事件回调没有反应

### ISSUE THREAD

**Issue by shiqiangdva** [1035901787/react-native-s-baidumap#4]
如标题所示, onMarkerClick方法事件回调没有反应,我该怎么办?

**Comment by shiqiangdva** [comment]
![image](https://user-images.githubusercontent.com/24239375/75955762-79188200-5ef1-11ea-9511-f0c6f5bc2df2.png)
onMarkerClick事件没有反应, 请问是什么原因导致?

**Comment by 1035901787** [comment]
这个事件没有业务场景需要，所以没有写
