### ISSUE TITLE
IOS端 地图点位icon 图标部分错误

### ISSUE THREAD

**Issue by shiqiangdva** [1035901787/react-native-s-baidumap#5]
![image](https://user-images.githubusercontent.com/24239375/75953535-85e6a700-5eec-11ea-8af8-80003f0761a7.png)
IOS端, 如图沈阳的地图图标有误, 不知道这图标从何而来

**Comment by 1035901787** [comment]
提供一下代码

**Comment by shiqiangdva** [comment]
`{
                        this.state.dianMap ?
                            this.state.testData.map((tmp, index) => {
                                if (tmp) {
                                    return (<Marker
                                        icon={require('../../resources/img/new-data/dianwei2.png')}
                                        location={{
                                            latitude: tmp.latitude,
                                            longitude: tmp.longitude
                                        }}
                                        active={true}
                                        title={tmp.title}
                                    />)
                                }
                            }) : null
                    }`
再写Demo, 就是在render中循环一个Marker点位list数组, Android中没有问题, 但是IOS端第一个Marker点就会变成这样

**Comment by shiqiangdva** [comment]
![image](https://user-images.githubusercontent.com/24239375/75955587-2048e980-5ef1-11ea-81b4-ed27ab1b4e03.png)

再写Demo, 就是在render中循环一个Marker点位的list数组, Android中显示没有问题, 但是IOS端的第一个Marker点就会变成这样

**Comment by 1035901787** [comment]
![image](https://user-images.githubusercontent.com/17847087/75956108-28555900-5ef2-11ea-9752-ad61d4773931.png)
![image](https://user-images.githubusercontent.com/17847087/75956120-330fee00-5ef2-11ea-94e5-60620f67f8b8.png)
我这边没有问题

**Comment by shiqiangdva** [comment]
这个是在地图放大或缩小到一定级别后, 根据业务需求, 重新setState中Marker的点位集合后, 新的集合的第一个Marker点的Icon就会出现异常。 如果自始至终Marker的集合不变地图缩放或放大是不会有这个异常的。

**Comment by shiqiangdva** [comment]
![image](https://user-images.githubusercontent.com/24239375/76140540-976bb280-6096-11ea-9272-9f2ebc29f3b4.png)
部分坐标还有问题
