### ISSUE TITLE
searchInCity城市内搜索和requestSuggestion关键字搜索输入框文字删除的时候重复调用会报错

### ISSUE THREAD

**Issue by GitXwj** [1035901787/react-native-s-baidumap#8]
`Illegal callback invocation from native module. This callback type only permits a single invocation from native code.`
原因是这两个函数原生通讯使用的是Promises回调，应该换成RCTEventEmitter发送通知的方式。

**Comment by 1035901787** [comment]
最新版本已经修复该问题

**Comment by GitXwj** [comment]
ios下还是有该问题，查看源码看见还是用的回调
